notas <- c(6.75,4,8,9,7,3,8)
sumary(notas)      
summary(notas)
mean(notas)
median(notas)
var(notas)
sd(notas)
sqrt(var(notas))
p.25 <- quantile(notas,probs = 0.25)
p.75<- quantile(notas, probs = 0.75)
table(iris$Species)
prop.table(table(iris$Species))
mean(iris$Sepal.Length)
median(iris$Sepal.Length)
quantile(iris$Species,0.25)
quantile(iris$Sepal.Length,probs = 0.25)
quantile(iris$Sepal.Length, probs = 0.95)
sd(iris$Sepal.Length)
summary(iris)
pacmam::p_load(fbasic)
pacman::p_load(fbasics)
basicstats(iris[, c(1:4)])
